[{"\u00e9quipe": "087", "score": 95, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"Une erreur s'est produite lors du formatage des donn\u00e9es re\u00e7ues:\", ' \u00ab Format de donn\u00e9es inattendu:', \"{'Note': 'Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.'} \u00bb\"]\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689910')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23582164')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"Une erreur s'est produite lors du formatage des donn\u00e9es re\u00e7ues:\", ' \u00ab Format de donn\u00e9es inattendu:', \"{'Note': 'Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.'} \u00bb\"]\n\n</pre>"}, {"\u00e9quipe": "111", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 127, in <module>\\n    output_text()\\n  File \"projet1.py\", line 100, in output_text\\n    last = list(res[\\'Time Series (Daily)\\'].keys())[-1].split(\\'-\\')\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "067", "score": 90, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800'), ('2018-11-23', '1023.8800')]\"]\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '684862')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23488031')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '684862'), ('2018-11-23', '684862')]\"]\n\n</pre>"}, {"\u00e9quipe": "068", "score": 22, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', ' [(2018-07-24, 1248.0800), (2018-09-24, 1173.3700)]']\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', ' [(2018-11-23, 1023.8800), (2018-11-23, 1023.8800)]']\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '685245')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23495610')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', ' [(2018-11-23, 684862), (2018-11-23, 684862)]']\n\n</pre>"}, {"\u00e9quipe": "069", "score": 16, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', ' [(2018-07-24, 1173.3700), (2018-09-24, 1173.3700)]']\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 141, in <module>\n    print(affichage())\n  File \"projet1.py\", line 131, in affichage\n    return sortie1(response['Time Series (Daily)'], chaine_tansformation(),\n  File \"projet1.py\", line 114, in chaine_tansformation\n    chaine1 = chaine.split('-')\nAttributeError: 'NoneType' object has no attribute 'split'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', ' [(2018-09-21, 4405584), (2018-09-24, 1271017)]']\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 141, in <module>\n    print(affichage())\n  File \"projet1.py\", line 131, in affichage\n    return sortie1(response['Time Series (Daily)'], chaine_tansformation(),\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "070", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "071", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 90, in <module>\\n    main()\\n  File \"projet1.py\", line 87, in main\\n    symbol.parse_values(api_helper.get(symbol_name, full_format))\\n  File \"/mnt/Documents/Projets/Laval/TA/Partie2/unbundled/bundle-071-03.hg/api.py\", line 46, in get\\n    \"Le symbole \\'{}\\' n\\'est surement pas valide.\".format(symbol)\\nValueError: Une erreur s\\'est produite pendant la r\u00e9cup\u00e9ration des donn\u00e9es sur l\\'API. Le symbole \\'goog\\' n\\'est surement pas valide.\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "072", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 86, in <module>\\n    Projet1().action_jour()\\n  File \"projet1.py\", line 79, in action_jour\\n    if response[\\'Time Series (Daily)\\'].get(str(instant.date())) is not None:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "073", "score": 100, "commentaires": ""}, {"\u00e9quipe": "074", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 105, in <module>\\n    fct_stock(ARGS.symbole)\\n  File \"projet1.py\", line 98, in fct_stock\\n    if i in response[\"Time Series (Daily)\"]:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "078", "score": 98, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689849')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23569407')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '685247')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\n\n</pre>"}, {"\u00e9quipe": "079", "score": 70, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture,2018-07-24,2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 61, in <module>\n    INTERVALLE = date.today() - changerdate(DEBUT)\n  File \"projet1.py\", line 57, in changerdate\n    new = x.split('-')\nAttributeError: 'datetime.date' object has no attribute 'split'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {'ouverture', 'max', 'volume', 'fermeture', 'min'}]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689849')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23575384')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 61, in <module>\n    INTERVALLE = date.today() - changerdate(DEBUT)\n  File \"projet1.py\", line 57, in changerdate\n    new = x.split('-')\nAttributeError: 'datetime.date' object has no attribute 'split'\n\n\n</pre>"}, {"\u00e9quipe": "080", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "082", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py.py [-h] [-d DEBUT] [-f FIN]\n                     [-v {fermeture,ouverture,volume,maximum,minimum}]\n                     symbole [symbole ...]\nprojet1.py.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "083", "score": 74, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"goog ('fermeture', '2018-07-24', '2018-09-24')\", \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 103, in <module>\n    finalpart1(ARGS.Symbole, ARGS.d, ARGS.f, ARGS.valeur)\n  File \"projet1.py\", line 88, in finalpart1\n    data = get_data(symb[symbole])[\"Time Series (Daily)\"]\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 103, in <module>\n    finalpart1(ARGS.Symbole, ARGS.d, ARGS.f, ARGS.valeur)\n  File \"projet1.py\", line 69, in finalpart1\n    dico = get_data(symb[0])[\"Time Series (Daily)\"]\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n [\"goog ('volume', '2018-11-23', '2018-11-23')\", \"[('2018-11-23', '689908')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 103, in <module>\n    finalpart1(ARGS.Symbole, ARGS.d, ARGS.f, ARGS.valeur)\n  File \"projet1.py\", line 88, in finalpart1\n    data = get_data(symb[symbole])[\"Time Series (Daily)\"]\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "084", "score": 28, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"Ce symbole n'existe pas ou trop de requ\u00eates ont \u00e9t\u00e9 effectu\u00e9es\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"Ce symbole n'existe pas ou trop de requ\u00eates ont \u00e9t\u00e9 effectu\u00e9es\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"Ce symbole n'existe pas ou trop de requ\u00eates ont \u00e9t\u00e9 effectu\u00e9es\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"Ce symbole n'existe pas ou trop de requ\u00eates ont \u00e9t\u00e9 effectu\u00e9es\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "085", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 75, in <module>\\n    fonction_principale()\\n  File \"Projet1.py\", line 68, in fonction_principale\\n    response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "086", "score": 81, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 53, in <module>\n    args.datedebut = datetime.datetime.strptime(args.datedebut, '%Y-%m-%d').date()\nTypeError: strptime() argument 1 must be str, not datetime.date\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689910')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23582164')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 53, in <module>\n    args.datedebut = datetime.datetime.strptime(args.datedebut, '%Y-%m-%d').date()\nTypeError: strptime() argument 1 must be str, not datetime.date\n\n\n</pre>"}, {"\u00e9quipe": "089", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "090", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "091", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 5, in <module>\\n    parser.add_argument(\\'symbole\\', dest=\\'symb\\', nargs=\\'+\\',type=list, help=\\'Nom du symbole boursier d\u00e9sir\u00e9\\')\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1334, in add_argument\\n    raise ValueError(\\'dest supplied twice for positional argument\\')\\nValueError: dest supplied twice for positional argument\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "092", "score": 88, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, 2018-09-24, 2018-10-01)\", \"[('2018-09-24', '1173.3700'), ('2018-09-25', '1184.6500'), ('2018-09-26', '1180.4900'), ('2018-09-27', '1194.6400'), ('2018-09-28', '1193.4700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, 2018-09-24, 2018-10-01)\", \"[('2018-09-24', '1173.3700'), ('2018-09-25', '1184.6500'), ('2018-09-26', '1180.4900'), ('2018-09-27', '1194.6400'), ('2018-09-28', '1193.4700')]\"]\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](volume, 2018-09-24, 2018-10-01)\", \"[('2018-09-24', '1271017'), ('2018-09-25', '977731'), ('2018-09-26', '1462253'), ('2018-09-27', '1260754'), ('2018-09-28', '1380629')]\"]\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689910')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23586225')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog', 'aapl'](volume, 2018-09-24, 2018-10-01)\", \"[('2018-09-24', '27693358'), ('2018-09-25', '24554379'), ('2018-09-26', '23984706'), ('2018-09-27', '30181227'), ('2018-09-28', '22929364')]\"]\n\n</pre>"}, {"\u00e9quipe": "093", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 110, in <module>\\n    retour.append(tuple(key_date, response[key_date][valeur]))\\nKeyError: \\'2018-09-21\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "094", "score": 70, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 37, in <module>\n    DATEDEBUTLISTE = ARGS.dateDebut.split('-')\nAttributeError: 'datetime.date' object has no attribute 'split'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689910')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23587369')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 37, in <module>\n    DATEDEBUTLISTE = ARGS.dateDebut.split('-')\nAttributeError: 'datetime.date' object has no attribute 'split'\n\n\n</pre>"}, {"\u00e9quipe": "096", "score": 81, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 50, in <module>\n    DEB = s2date(ARGS.d)\n  File \"projet1.py\", line 45, in s2date\n    if len(chdate) == 10:\nTypeError: object of type 'datetime.date' has no len()\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '690247')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23594385')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole\nprojet1.py: error: unrecognized arguments: aapl\n\n\n</pre>"}, {"\u00e9quipe": "097", "score": 76, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture,2018-07-24,2018-09-24)', \"[('2018-09-24', '1173.3700'), ('2018-09-21', '1166.0900'), ('2018-09-20', '1186.8700'), ('2018-09-19', '1171.0900'), ('2018-09-18', '1161.2200'), ('2018-09-17', '1156.0500'), ('2018-09-14', '1172.5300'), ('2018-09-13', '1175.3300'), ('2018-09-12', '1162.8200'), ('2018-09-11', '1177.3600'), ('2018-09-10', '1164.6400'), ('2018-09-07', '1164.8300'), ('2018-09-06', '1171.4400'), ('2018-09-05', '1186.4800'), ('2018-09-04', '1197.0000'), ('2018-08-31', '1218.1900'), ('2018-08-30', '1239.1200'), ('2018-08-29', '1249.3000'), ('2018-08-28', '1231.1500'), ('2018-08-27', '1241.8200'), ('2018-08-24', '1220.6500'), ('2018-08-23', '1205.3800'), ('2018-08-22', '1207.3300'), ('2018-08-21', '1201.6200'), ('2018-08-20', '1207.7700'), ('2018-08-17', '1200.9600'), ('2018-08-16', '1206.4900'), ('2018-08-15', '1214.3800'), ('2018-08-14', '1242.1000'), ('2018-08-13', '1235.0100'), ('2018-08-10', '1237.6100'), ('2018-08-09', '1249.1000'), ('2018-08-08', '1245.6100'), ('2018-08-07', '1242.2200'), ('2018-08-06', '1224.7700'), ('2018-08-03', '1223.7100'), ('2018-08-02', '1226.1500'), ('2018-08-01', '1220.0100'), ('2018-07-31', '1217.2600'), ('2018-07-30', '1219.7400'), ('2018-07-27', '1238.5000'), ('2018-07-26', '1268.3300'), ('2018-07-25', '1263.7000'), ('2018-07-24', '1248.0800')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 101, in <module>\n    INFORMATION = get_info(ARG_SYMBOL, ARGS.debut, ARGS.fin)\n  File \"projet1.py\", line 15, in get_info\n    d1 = datetime.strptime(date_debut, \"%Y-%m-%d\")\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/_strptime.py\", line 577, in _strptime_datetime\n    tt, fraction, gmtoff_fraction = _strptime(data_string, format)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/_strptime.py\", line 359, in _strptime\n    (data_string, format))\nValueError: time data '' does not match format '%Y-%m-%d'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume,2018-09-21,2018-09-24)', \"[('2018-09-24', '1271017'), ('2018-09-21', '4405584')]\"]\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '690247')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23595658')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol [symbole ...]\nprojet1.py: error: unrecognized arguments: aapl\n\n\n</pre>"}, {"\u00e9quipe": "098", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 10, in <module>\\n    description=\"Le programme courant affiche les valeurs de diff\u00e9rentes actions boursi\u00e8res.\")\\nNameError: name \\'ArgumentParser\\' is not defined\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "099", "score": 94, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 64, in <module>\n    dico = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "100", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "102", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "103", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 99, in <module>\\n    tuplefinal(debut, fin, alpha_vantage(i))\\n  File \"projet1.py\", line 89, in tuplefinal\\n    if str(debut1) in response[\\'Time Series (Daily)\\'].keys():\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "104", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 80, in <module>\\n    dico_dates = reponse[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "105", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "106", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"PROJET1.py\", line 70, in <module>\\n    print(affichage(ARGS.valeur, ARGS.debut, ARGS.fin, ARGS.symbole))\\n  File \"PROJET1.py\", line 65, in affichage\\n    ligne2 = \\'{}\\\\n {}\\'.format(ligne1, fonction_1(valeur, debut, fin, symbole))\\n  File \"PROJET1.py\", line 55, in fonction_1\\n    sortie1 = (debut, response[\\'Time Series (Daily)\\'][debut][valeur])\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "113", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "114", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 106, in <module>\\n    val = response[\"Time Series (Daily)\"][j][type_val]\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "115", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "118", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 107, in <module>\\n    final(symbole, nombre_de_jours, d\u00e9but)\\n  File \"projet1.py\", line 87, in final\\n    if date not in response[\\'Time Series (Daily)\\']:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "119", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 126, in <module>\\n    response[\\'Time Series (Daily)\\'][date_d\u00e9but_tempo][key_in_api(ARGS.valeur)])\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "120", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 127, in <module>\\n    chercherdansledictionnaire()\\n  File \"projet1.py\", line 116, in chercherdansledictionnaire\\n    listefinale.append((str(m), ss[\\'Time Series (Daily)\\'][str(m)][\"5. volume\"]))\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "122", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 100, in <module>\\n    donnees = interroger_alpha_vantage(symbole, TAILLE)\\n  File \"projet1.py\", line 71, in interroger_alpha_vantage\\n    return response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "123", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 53, in <module>\\n    ouvdeb = response[\\'Time Series (Daily)\\'][debut][\\'1. open\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "124", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 8, in <module>\\n    import numpy\\nModuleNotFoundError: No module named \\'numpy\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "125", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 93, in <module>\\n    OUT.append((PRM.debut, ANS[\\'Time Series (Daily)\\'][PRM.debut][VAL[PRM.valeur]]))\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "126", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connection.py\", line 171, in _new_conn\\n    (self._dns_host, self.port), self.timeout, **extra_kw)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/util/connection.py\", line 56, in create_connection\\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/socket.py\", line 748, in getaddrinfo\\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\\nsocket.gaierror: [Errno -2] Name or service not known\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 600, in urlopen\\n    chunked=chunked)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 343, in _make_request\\n    self._validate_conn(conn)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 849, in _validate_conn\\n    conn.connect()\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connection.py\", line 314, in connect\\n    conn = self._new_conn()\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connection.py\", line 180, in _new_conn\\n    self, \"Failed to establish a new connection: %s\" % e)\\nurllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f9af0b7a550>: Failed to establish a new connection: [Errno -2] Name or service not known\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/requests/adapters.py\", line 449, in send\\n    timeout=timeout\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 638, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/urllib3/util/retry.py\", line 398, in increment\\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\\'www.aplhavantage.co\\', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_DAILY&apikey=G34DOS61ZFYB99FI&outputsize=compact&symbol=goog (Caused by NewConnectionError(\\'<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9af0b7a550>: Failed to establish a new connection: [Errno -2] Name or service not known\\'))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"projet1.py\", line 121, in <module>\\n    afficher(ARGS.debut, ARGS.fin, ARGS.symbole, ARGS.valeur)\\n  File \"projet1.py\", line 118, in afficher\\n    print(liste_date_valeur(debut, fin, symbole, valeur))\\n  File \"projet1.py\", line 98, in liste_date_valeur\\n    response = requests.get(url=URL, params=params)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/requests/api.py\", line 75, in get\\n    return request(\\'get\\', url, params=params, **kwargs)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/requests/api.py\", line 60, in request\\n    return session.request(method=method, url=url, **kwargs)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/requests/sessions.py\", line 524, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/requests/sessions.py\", line 637, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/site-packages/requests/adapters.py\", line 516, in send\\n    raise ConnectionError(e, request=request)\\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host=\\'www.aplhavantage.co\\', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_DAILY&apikey=G34DOS61ZFYB99FI&outputsize=compact&symbol=goog (Caused by NewConnectionError(\\'<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9af0b7a550>: Failed to establish a new connection: [Errno -2] Name or service not known\\'))\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "127", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "128", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 48, in <module>\\n    new_dict = response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "129", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "130", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n[\"Votre erreur est :  usage: projet1.py [-h] [-f DATE] [-d DATE]\\n                  [-v  {fermeture,ouverture,min,max,volume}]\\n                  symbole [symbole ...]\\nprojet1.py: error: unrecognized arguments: -v=volume\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\\n\"] </pre>"}, {"\u00e9quipe": "131", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 94, in <module>\\n    print(trouver_valeur(DATE_INITIALE, DATE_FINALE, reponse))\\n  File \"projet1.py\", line 84, in trouver_valeur\\n    donnees_date1 = response[\\'Time Series (Daily)\\'].get(str(date1), False)\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "132", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 93, in <module>\\n    dictio = response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "133", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 99, in <module>\\n    temp = response[\"Time Series (Daily)\"][i][KeyValeur[args.valeur]]\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "134", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 107, in <module>\\n    dico_TSD = response[\\'Time Series (Daily)\\']  # dico_TSD est le dictionnaire obtenu\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "135", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "136", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 52, in <module>\\n    print(format(args))\\n  File \"projet1.py\", line 47, in format\\n    a = response[\\'Time Series (Daily)\\'][date_generated]\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "137", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]', '']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]', '']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]', '']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', '', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]', '']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "139", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "140", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 68, in <module>\\n    L = RESPONSE[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "141", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 76, in <module>\\n    response = json.loads((requests.get(url=url, params=params)).text)[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "142", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 107, in <module>\\n    affichage(K, ARGS.valeur, ARGS.debut, ARGS.fin, FORMAT)\\n  File \"projet1.py\", line 49, in affichage\\n    print(formatage(extraction(symbole, typeformat), debut, fin, valeur))\\n  File \"projet1.py\", line 30, in formatage\\n    for k in bourse[\\'Time Series (Daily)\\'].keys():\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}]