[{"\u00e9quipe": "163", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :    File \"projet1.py\", line 62\\n    def affichage:\\n                 ^\\nSyntaxError: invalid syntax\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "184", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :    File \"projet1.py\", line 52\\n    return reponse\\n    ^\\nSyntaxError: \\'return\\' outside function\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "144", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 90, in <module>\\n    print([(str(DATE_DEBUT), LISTE_VALEURS[0]), (str(DATE_FIN), LISTE_VALEURS[-1])])\\nIndexError: list index out of range\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "145", "score": 92, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '684862')]\", 'aapl(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '684862')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "146", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "147", "score": 66, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\n\n</pre>"}, {"\u00e9quipe": "148", "score": 82, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, 2018-07-24, 2018-09-24)\", \"[('2018-07-24', '1248.0800'), ('2018-07-26', '1268.3300'), ('2018-07-30', '1219.7400'), ('2018-08-01', '1220.0100'), ('2018-08-03', '1223.7100'), ('2018-08-07', '1242.2200'), ('2018-08-09', '1249.1000'), ('2018-08-13', '1235.0100'), ('2018-08-15', '1214.3800'), ('2018-08-17', '1200.9600'), ('2018-08-21', '1201.6200'), ('2018-08-23', '1205.3800'), ('2018-08-27', '1241.8200'), ('2018-08-29', '1249.3000'), ('2018-08-31', '1218.1900'), ('2018-09-05', '1186.4800'), ('2018-09-07', '1164.8300'), ('2018-09-11', '1177.3600'), ('2018-09-13', '1175.3300'), ('2018-09-17', '1156.0500'), ('2018-09-19', '1171.0900'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700'), ('2018-09-20', '1186.8700'), ('2018-09-18', '1161.2200'), ('2018-09-14', '1172.5300'), ('2018-09-12', '1162.8200'), ('2018-09-10', '1164.6400'), ('2018-09-06', '1171.4400'), ('2018-09-04', '1197.0000'), ('2018-08-30', '1239.1200'), ('2018-08-28', '1231.1500'), ('2018-08-24', '1220.6500'), ('2018-08-22', '1207.3300'), ('2018-08-20', '1207.7700'), ('2018-08-16', '1206.4900'), ('2018-08-14', '1242.1000'), ('2018-08-10', '1237.6100'), ('2018-08-08', '1245.6100'), ('2018-08-06', '1224.7700'), ('2018-08-02', '1226.1500'), ('2018-07-31', '1217.2600'), ('2018-07-27', '1238.5000'), ('2018-07-25', '1263.7000')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, 2018-11-23, 2018-11-23)\", \"[('2018-11-23', '1023.8800')]\"]\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '685247')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23512626')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog', 'aapl'](volume, 2018-11-23, 2018-11-23)\", \"[('2018-11-23', '685247')]\", \"[('2018-11-23', '23512626')]\"]\n\n</pre>"}, {"\u00e9quipe": "149", "score": 22, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', 1248.0800), ('2018-07-25', 1263.7000), ('2018-07-26', 1268.3300), ('2018-07-27', 1238.5000), ('2018-07-30', 1219.7400), ('2018-07-31', 1217.2600), ('2018-08-01', 1220.0100), ('2018-08-02', 1226.1500), ('2018-08-03', 1223.7100), ('2018-08-06', 1224.7700), ('2018-08-07', 1242.2200), ('2018-08-08', 1245.6100), ('2018-08-09', 1249.1000), ('2018-08-10', 1237.6100), ('2018-08-13', 1235.0100), ('2018-08-14', 1242.1000), ('2018-08-15', 1214.3800), ('2018-08-16', 1206.4900), ('2018-08-17', 1200.9600), ('2018-08-20', 1207.7700), ('2018-08-21', 1201.6200), ('2018-08-22', 1207.3300), ('2018-08-23', 1205.3800), ('2018-08-24', 1220.6500), ('2018-08-27', 1241.8200), ('2018-08-28', 1231.1500), ('2018-08-29', 1249.3000), ('2018-08-30', 1239.1200), ('2018-08-31', 1218.1900), ('2018-09-04', 1197.0000), ('2018-09-05', 1186.4800), ('2018-09-06', 1171.4400), ('2018-09-07', 1164.8300), ('2018-09-10', 1164.6400), ('2018-09-11', 1177.3600), ('2018-09-12', 1162.8200), ('2018-09-13', 1175.3300), ('2018-09-14', 1172.5300), ('2018-09-17', 1156.0500), ('2018-09-18', 1161.2200), ('2018-09-19', 1171.0900), ('2018-09-20', 1186.8700), ('2018-09-21', 1166.0900), ('2018-09-24', 1173.3700)]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', 1023.8800)]\"]\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '685247')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23512626')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', 685247)]\", 'aapl(volume, 2018-11-23, 2018-11-23)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 78, in <module>\n    if date.strftime(\"%Y-%m-%d\") in RESPONSE['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "150", "score": 79, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "151", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n[\"Votre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\\n                  [-v {fermeture, ouverture, min, max, volume} valeur]\\n                  symbol [symbol ...]\\nprojet1.py: error: unrecognized arguments: -v=volume\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\\n\"] </pre>"}, {"\u00e9quipe": "152", "score": 78, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"goog(['fermeture'], 2018-07-24, 2018-09-24)\", \"Le march\u00e9 boursier n'a pas de donn\u00e9es au moins une des journ\u00e9es sp\u00e9cifi\u00e9s,ou il y a eu plus de 5 requ\u00e8tes dans la derni\u00e8re minute.\", 'Changer les dates ou attendre pour avoir un r\u00e9sultat valide.']\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"goog(['fermeture'], 2018-11-23, 2018-11-23)\", \"Le march\u00e9 boursier n'a pas de donn\u00e9es au moins une des journ\u00e9es sp\u00e9cifi\u00e9s,ou il y a eu plus de 5 requ\u00e8tes dans la derni\u00e8re minute.\", 'Changer les dates ou attendre pour avoir un r\u00e9sultat valide.']\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: Projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v {ouverture, fermeture, min, max, volume} [{ouverture, fermeture, min, max, volume} ...]]\n                  symbole [symbole ...]\nProjet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689849')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23570780')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: Projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v {ouverture, fermeture, min, max, volume} [{ouverture, fermeture, min, max, volume} ...]]\n                  symbole [symbole ...]\nProjet1.py: error: argument -v/--valeur: invalid choice: 'goog' (choose from 'ouverture', 'fermeture', 'min', 'max', 'volume')\n\n\n</pre>"}, {"\u00e9quipe": "153", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "154", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "155", "score": 82, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24) ', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23) ', \"[('2018-11-23', '1023.8800')]\"]\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23) ', \"[('2018-11-23', '689849')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 80, in <module>\n    answer = para(k, TIMELAPSE_DAYS)\n  File \"projet1.py\", line 75, in para\n    demand = responsed['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "157", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "159", "score": 82, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture,2018-07-24,2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture,2018-11-23,2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689908')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23579398')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume,2018-11-23,2018-11-23)', '[]', 'aapl(volume,2018-11-23,2018-11-23)', '[]']\n\n</pre>"}, {"\u00e9quipe": "161", "score": 10, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24, '1248.0800')], ('2018-09-24, '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 66, in <module>\n    openD = response['Time Series (Daily)'][debut]['1. open']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 66, in <module>\n    openD = response['Time Series (Daily)'][debut]['1. open']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "162", "score": 79, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 39, in <module>\n    ARGS.DATE = [ARGS.DATE[0], ARGS.DATE[0]] if len(ARGS.DATE) == 1 else ARGS.DATE\nTypeError: object of type 'NoneType' has no len()\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-24, 2018-09-21)', '[]']\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689910')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23582164')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 39, in <module>\n    ARGS.DATE = [ARGS.DATE[0], ARGS.DATE[0]] if len(ARGS.DATE) == 1 else ARGS.DATE\nTypeError: object of type 'NoneType' has no len()\n\n\n</pre>"}, {"\u00e9quipe": "164", "score": 79, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 106, in <module>\n    formaterreponse(symbol, REPONSE, VALEUR, ARGS)\n  File \"projet1.py\", line 88, in formaterreponse\n    deuxiemeligne.append((datestr, response['Time Series (Daily)'][datestr][valeur]))\nKeyError: '2018-09-03'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol [symbol ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\n\n</pre>"}, {"\u00e9quipe": "166", "score": 100, "commentaires": ""}, {"\u00e9quipe": "167", "score": 22, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['2018-09-24', '2018-07-24', '62', 'compact', \"['2018-07-24', '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28', '2018-07-29', '2018-07-30', '2018-07-31', '2018-08-01', '2018-08-02', '2018-08-03', '2018-08-04', '2018-08-05', '2018-08-06', '2018-08-07', '2018-08-08', '2018-08-09', '2018-08-10', '2018-08-11', '2018-08-12', '2018-08-13', '2018-08-14', '2018-08-15', '2018-08-16', '2018-08-17', '2018-08-18', '2018-08-19', '2018-08-20', '2018-08-21', '2018-08-22', '2018-08-23', '2018-08-24', '2018-08-25', '2018-08-26', '2018-08-27', '2018-08-28', '2018-08-29', '2018-08-30', '2018-08-31', '2018-09-01', '2018-09-02', '2018-09-03', '2018-09-04', '2018-09-05', '2018-09-06', '2018-09-07', '2018-09-08', '2018-09-09', '2018-09-10', '2018-09-11', '2018-09-12', '2018-09-13', '2018-09-14', '2018-09-15', '2018-09-16', '2018-09-17', '2018-09-18', '2018-09-19', '2018-09-20', '2018-09-21', '2018-09-22', '2018-09-23', '2018-09-24']\", \"['1248.0800', '1263.7000', '1268.3300', '1238.5000', '1219.7400', '1217.2600', '1220.0100', '1226.1500', '1223.7100', '1224.7700', '1242.2200', '1245.6100', '1249.1000', '1237.6100', '1235.0100', '1242.1000', '1214.3800', '1206.4900', '1200.9600', '1207.7700', '1201.6200', '1207.3300', '1205.3800', '1220.6500', '1241.8200', '1231.1500', '1249.3000', '1239.1200', '1218.1900', '1197.0000', '1186.4800', '1171.4400', '1164.8300', '1164.6400', '1177.3600', '1162.8200', '1175.3300', '1172.5300', '1156.0500', '1161.2200', '1171.0900', '1186.8700', '1166.0900', '1173.3700']\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['2018-11-23', '2018-11-23', '0', 'compact', \"['2018-11-23']\", \"['1023.8800']\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture, ouverture, min, max, volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689910')]\", 'aapl(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['2018-11-23', '2018-11-23', '0', 'compact', \"['2018-11-23']\", '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "168", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "169", "score": 77, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '690247')]\", 'aapl(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "170", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 84, in <module>\\n    REP = parametre(i)\\n  File \"projet1.py\", line 79, in parametre\\n    rep_demand = response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "171", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 11, in <module>\\n    import pandas as  pd\\nModuleNotFoundError: No module named \\'pandas\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "172", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 85, in <module>\\n    sortie(OUVRE, FERME, SYMBOL)\\n  File \"projet1.py\", line 65, in sortie\\n    if str(listedate) in response[\\'Time Series (Daily)\\']:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "173", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :    File \"Projet1.py\", line 69\\n    elif args.valeur == \\'volume\\'\\n                               ^\\nSyntaxError: invalid syntax\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "174", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :    File \"projet1.py\", line 41\\n    for s in date.(\"-\"):\\n                  ^\\nSyntaxError: invalid syntax\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "175", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "178", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 79, in <module>\\n    AFF = RESPONSE[\\'Time Series (Daily)\\'][\\'{}\\'.format(DATE)]\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "179", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 70, in <module>\\n    valeurjours()\\n  File \"projet1.py\", line 62, in valeurjours\\n    if response[\\'Time Series (Daily)\\'].get(str(date1)) is not None:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "180", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "181", "score": 88, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24) ', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23) ', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24) ', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23) ', '[]', 'aapl(volume, 2018-11-23, 2018-11-23) ', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "183", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 103, in <module>\\n    print(chercher_valeur(DATE_DEBUT, DATE_FIN, data))\\n  File \"projet1.py\", line 93, in chercher_valeur\\n    infos_date_courante = response[\\'Time Series (Daily)\\'].get(str(date_courante), False)\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "185", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "187", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 45, in <module>\n    DDEBUT = s2date(ARGS.datedebut)\n  File \"projet1.py\", line 41, in s2date\n    year, month, day = map(int, value.split('-'))\nValueError: invalid literal for int() with base 10: 'date.today()'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 45, in <module>\n    DDEBUT = s2date(ARGS.datedebut)\n  File \"projet1.py\", line 41, in s2date\n    year, month, day = map(int, value.split('-'))\nValueError: invalid literal for int() with base 10: 'date.today()'\n\n\n</pre>"}, {"\u00e9quipe": "188", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 110, in <module>\\n    affichage(filtrage(ARGS.debut, ARGS.fin, ARGS.valeur))\\n  File \"Projet1.py\", line 80, in filtrage\\n    for d in info[\\'Time Series (Daily)\\'].keys():\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "189", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 39, in <module>\\n    d = datetime.date(int(args.debut))\\nValueError: invalid literal for int() with base 10: \\'2018-09-21\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "190", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "191", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 64, in <module>\\n    for i in RESPONSE[\\'Time Series (Daily)\\']:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "192", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 83, in <module>\\n    recup_dico(ARGS.symbole, VALEUR_DEBUT, VALEUR_FIN, ARGS.valeur)\\n  File \"projet1.py\", line 60, in recup_dico\\n    response = response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "193", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 99, in <module>\\n    a = response[\\'Time Series (Daily)\\'][args.d][\\'5. volume\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "194", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "195", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "196", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 121, in <module>\\n    main()\\n  File \"projet1.py\", line 113, in main\\n    liste_empty.append((str(m), s[\\'Time Series (Daily)\\'][str(m)][\"5. volume\"]))\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "198", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "200", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "201", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 42, in <module>\\n    DONNEES = AlphaVantageAPI.telecharger_donnees(sym, DEB_A_AJD)\\n  File \"/mnt/Documents/Projets/Laval/TA/Partie3/unbundled/bundle-201-13.hg/AlphaVantageAPI.py\", line 28, in telecharger_donnees\\n    return response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "202", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "203", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 128, in <module>\\n    generer_liste_valeurs()\\n  File \"projet1.py\", line 90, in generer_liste_valeurs\\n    sy = fsym[j]\\nIndexError: list index out of range\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "204", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 76, in <module>\\n    liste_reponse.append((response[\\'Time Series (Daily)\\'][j])[cle_valeur(ARGS.valeur)])\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "208", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 94, in <module>\\n    action(DATE_INITIALE, DATE_FINALE, SYMBOL)\\n  File \"projet1.py\", line 70, in action\\n    if str(date_sauce) in response[\\'Time Series (Daily)\\']:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "209", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "210", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 138, in <module>\\n    l2 = ligne2(args.valeur, args.d, args.f)\\n  File \"projet1.py\", line 114, in ligne2\\n    time_series = response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "212", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 108, in <module>\\n    z = response[\\'Meta Data\\'][\\'2. Symbol\\']\\nKeyError: \\'Meta Data\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "213", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "214", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 80, in <module>\\n    display(args)\\n  File \"Projet1.py\", line 50, in display\\n    for value in response[\\'Time Series (Daily)\\'].keys():\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "215", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 44, in <module>\\n    parse_valeur()\\n  File \"projet1.py\", line 19, in parse_valeur\\n    default=\\'Help\\', help=\\'show this help message and exit\\'\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1367, in add_argument\\n    return self._add_action(action)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1730, in _add_action\\n    self._optionals._add_action(action)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1571, in _add_action\\n    action = super(_ArgumentGroup, self)._add_action(action)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1381, in _add_action\\n    self._check_conflict(action)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1520, in _check_conflict\\n    conflict_handler(action, confl_optionals)\\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1529, in _handle_conflict_error\\n    raise ArgumentError(action, message % conflict_string)\\nargparse.ArgumentError: argument -h: conflicting option string: -h\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "216", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 87, in <module>\\n    print(sortie(ARGS.valeur))\\n  File \"Projet1.py\", line 78, in sortie\\n    for key, value in sorted(RESPONSE[\\'Time Series (Daily)\\'].items()):\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "217", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 67, in <module>\\n    infosalpha(ARFC.symbole, ARFC.deb, ARFC.fin, ARFC.val, outputsize=\\'compact\\')\\n  File \"Projet1.py\", line 57, in infosalpha\\n    if response[\\'Time Series (Daily)\\'].get(date.__str__(dd)) is None:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}]