[{"\u00e9quipe": "187", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 45, in <module>\n    DDEBUT = s2date(ARGS.datedebut)\n  File \"projet1.py\", line 41, in s2date\n    year, month, day = map(int, value.split('-'))\nValueError: invalid literal for int() with base 10: 'date.today()'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 45, in <module>\n    DDEBUT = s2date(ARGS.datedebut)\n  File \"projet1.py\", line 41, in s2date\n    year, month, day = map(int, value.split('-'))\nValueError: invalid literal for int() with base 10: 'date.today()'\n\n\n</pre>"}, {"\u00e9quipe": "188", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"Projet1.py\", line 110, in <module>\n    affichage(filtrage(ARGS.debut, ARGS.fin, ARGS.valeur))\n  File \"Projet1.py\", line 80, in filtrage\n    for d in info['Time Series (Daily)'].keys():\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "189", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 39, in <module>\n    d = datetime.date(int(args.debut))\nValueError: invalid literal for int() with base 10: '2018-09-21'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "190", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "191", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 64, in <module>\n    for i in RESPONSE['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "192", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 83, in <module>\n    recup_dico(ARGS.symbole, VALEUR_DEBUT, VALEUR_FIN, ARGS.valeur)\n  File \"projet1.py\", line 60, in recup_dico\n    response = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "193", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 99, in <module>\n    a = response['Time Series (Daily)'][args.d]['5. volume']\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "194", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "195", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "196", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 121, in <module>\n    main()\n  File \"projet1.py\", line 113, in main\n    liste_empty.append((str(m), s['Time Series (Daily)'][str(m)][\"5. volume\"]))\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "198", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "200", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "201", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 42, in <module>\n    DONNEES = AlphaVantageAPI.telecharger_donnees(sym, DEB_A_AJD)\n  File \"/mnt/Documents/Projets/Laval/TA/Partie7/unbundled/bundle-201-13.hg/AlphaVantageAPI.py\", line 28, in telecharger_donnees\n    return response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "202", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "203", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 128, in <module>\n    generer_liste_valeurs()\n  File \"projet1.py\", line 90, in generer_liste_valeurs\n    sy = fsym[j]\nIndexError: list index out of range\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "204", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 76, in <module>\n    liste_reponse.append((response['Time Series (Daily)'][j])[cle_valeur(ARGS.valeur)])\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "208", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 94, in <module>\n    action(DATE_INITIALE, DATE_FINALE, SYMBOL)\n  File \"projet1.py\", line 70, in action\n    if str(date_sauce) in response['Time Series (Daily)']:\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "209", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-24, 2018-11-24)', '[]', 'aapl(volume, 2018-11-24, 2018-11-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "210", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 138, in <module>\n    l2 = ligne2(args.valeur, args.d, args.f)\n  File \"projet1.py\", line 114, in ligne2\n    time_series = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "212", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 108, in <module>\n    z = response['Meta Data']['2. Symbol']\nKeyError: 'Meta Data'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "213", "score": 0, "commentaires": "<pre>Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle</pre>"}, {"\u00e9quipe": "214", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"Projet1.py\", line 80, in <module>\n    display(args)\n  File \"Projet1.py\", line 50, in display\n    for value in response['Time Series (Daily)'].keys():\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "215", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 44, in <module>\n    parse_valeur()\n  File \"projet1.py\", line 19, in parse_valeur\n    default='Help', help='show this help message and exit'\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1367, in add_argument\n    return self._add_action(action)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1730, in _add_action\n    self._optionals._add_action(action)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1571, in _add_action\n    action = super(_ArgumentGroup, self)._add_action(action)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1381, in _add_action\n    self._check_conflict(action)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1520, in _check_conflict\n    conflict_handler(action, confl_optionals)\n  File \"/home/pedro/.conda/envs/TA/lib/python3.7/argparse.py\", line 1529, in _handle_conflict_error\n    raise ArgumentError(action, message % conflict_string)\nargparse.ArgumentError: argument -h: conflicting option string: -h\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "216", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"Projet1.py\", line 87, in <module>\n    print(sortie(ARGS.valeur))\n  File \"Projet1.py\", line 78, in sortie\n    for key, value in sorted(RESPONSE['Time Series (Daily)'].items()):\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}, {"\u00e9quipe": "217", "score": 0, "commentaires": "<h3>Votre programme n'a pas fonctionn\u00e9 durant la correction...</h3><pre>Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\nVotre erreur est :  Traceback (most recent call last):\n  File \"Projet1.py\", line 67, in <module>\n    infosalpha(ARFC.symbole, ARFC.deb, ARFC.fin, ARFC.val, outputsize='compact')\n  File \"Projet1.py\", line 57, in infosalpha\n    if response['Time Series (Daily)'].get(date.__str__(dd)) is None:\nKeyError: 'Time Series (Daily)'\n\n\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\n</pre>"}]