[{"\u00e9quipe": "020", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 77, in <module>\\n    format_final(ARGS.symbole)\\n  File \"projet1.py\", line 75, in format_final\\n    deuxieme_ligne(k[symb])\\n  File \"projet1.py\", line 67, in deuxieme_ligne\\n    response[\\'Time Series (Daily)\\'][e][c],\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "038", "score": 82, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-05, 2018-11-23)', \"[('2018-07-05', '1023.8800'), ('2018-11-23', '1124.2700')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 100, in <module>\n    main()\n  File \"projet1.py\", line 35, in main\n    listdat = list(resp[\"Time Series (Daily)\"].keys())\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n [\"goog', 'aapl(volume, 2018-07-05, 2018-11-23)\", \"[('2018-07-05', '23595658'), ('2018-11-23', '16604248')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "001", "score": 92, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '684862')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23486970')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "003", "score": 73, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "004", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 78, in <module>\\n    tuplefinal(debut, fin, site(i))\\n  File \"projet1.py\", line 71, in tuplefinal\\n    uple1.append((str(debut1), response[\\'Time Series (Daily)\\'][str(debut1)][str(fct(valeur))]))\\nNameError: name \\'uple1\\' is not defined\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "006", "score": 70, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-07-25, 2018-07-26, 2018-07-27, 2018-07-30, 2018-07-31, 2018-08-01, 2018-08-02, 2018-08-03, 2018-08-06, 2018-08-07, 2018-08-08, 2018-08-09, 2018-08-10, 2018-08-13, 2018-08-14, 2018-08-15, 2018-08-16, 2018-08-17, 2018-08-20, 2018-08-21, 2018-08-22, 2018-08-23, 2018-08-24, 2018-08-27, 2018-08-28, 2018-08-29, 2018-08-30, 2018-08-31, 2018-09-04, 2018-09-05, 2018-09-06, 2018-09-07, 2018-09-10, 2018-09-11, 2018-09-12, 2018-09-13, 2018-09-14, 2018-09-17, 2018-09-18, 2018-09-19, 2018-09-20, 2018-09-21, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 42, in <module>\n    for i in range(0, len(args.DATE)):\nTypeError: object of type 'NoneType' has no len()\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '685245')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23506962')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 42, in <module>\n    for i in range(0, len(args.DATE)):\nTypeError: object of type 'NoneType' has no len()\n\n\n</pre>"}, {"\u00e9quipe": "007", "score": 73, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 98, in <module>\n    print(valeur_desiree(valeur))\n  File \"projet1.py\", line 85, in valeur_desiree\n    tupl = tuple((fin, str(response[\"Time Series (Daily)\"][fin][dico[valeur]])))\nTypeError: unhashable type: 'list'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f FIN]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '685245')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23509316')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f FIN]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbol\nprojet1.py: error: unrecognized arguments: aapl\n\n\n</pre>"}, {"\u00e9quipe": "008", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 95, in <module>\n    fonc(liste) ## fin TP 19 novembre\n  File \"projet1.py\", line 52, in fonc\n    v.append(response['Time Series (Daily)'][d[i]])\nKeyError: '2018-09-03'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 95, in <module>\n    fonc(liste) ## fin TP 19 novembre\n  File \"projet1.py\", line 78, in fonc\n    d[len(d)-1] = d[len(d)-1] + ')'\nIndexError: list index out of range\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '685247')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 84, in <module>\n    fonc(args.DATE)  # 14 novembre\n  File \"projet1.py\", line 45, in fonc\n    v_debut = response['Time Series (Daily)'][d[0]]\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "009", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 91, in <module>\\n    fonction(ARGS.symbole, ARGS.debut, ARGS.fin, ARGS.valeur)\\n  File \"projet1.py\", line 72, in fonction\\n    if str(une_date) in response[\\'Time Series (Daily)\\']:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "011", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "012", "score": 94, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '685247')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23512626')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "013", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "014", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 104, in <module>\\n    affichage(ARGS.symbole, ARGS.debut, ARGS.fin, ARGS.valeur)\\n  File \"projet1.py\", line 80, in affichage\\n    if str(delai) in response[\\'Time Series (Daily)\\']:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "015", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 100, in <module>\\n    valeur2 = dureepluspetite()[\\'Time Series (Daily)\\'][\\'{}\\'.format(datef)][clef]\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "016", "score": 28, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, 2018-07-24, 2018-09-24)\", 'Le symbole goog est indisponible.']\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](fermeture, None, None)\", 'goog:[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog'](volume, 2018-09-21, 2018-09-24)\", 'Le symbole goog est indisponible.']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n [\"['goog', 'aapl'](volume, None, None)\", 'Le symbole goog est indisponible.', 'Le symbole aapl est indisponible.']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "017", "score": 100, "commentaires": ""}, {"\u00e9quipe": "018", "score": 10, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-07-25', '1263.7000'), ('2018-07-26', '1268.3300'), ('2018-07-27', '1238.5000'), ('2018-07-30', '1219.7400'), ('2018-07-31', '1217.2600'), ('2018-08-01', '1220.0100'), ('2018-08-02', '1226.1500'), ('2018-08-03', '1223.7100'), ('2018-08-06', '1224.7700'), ('2018-08-07', '1242.2200'), ('2018-08-08', '1245.6100'), ('2018-08-09', '1249.1000'), ('2018-08-10', '1237.6100'), ('2018-08-13', '1235.0100'), ('2018-08-14', '1242.1000'), ('2018-08-15', '1214.3800'), ('2018-08-16', '1206.4900'), ('2018-08-17', '1200.9600'), ('2018-08-20', '1207.7700'), ('2018-08-21', '1201.6200'), ('2018-08-22', '1207.3300'), ('2018-08-23', '1205.3800'), ('2018-08-24', '1220.6500'), ('2018-08-27', '1241.8200'), ('2018-08-28', '1231.1500'), ('2018-08-29', '1249.3000'), ('2018-08-30', '1239.1200'), ('2018-08-31', '1218.1900'), ('2018-09-04', '1197.0000'), ('2018-09-05', '1186.4800'), ('2018-09-06', '1171.4400'), ('2018-09-07', '1164.8300'), ('2018-09-10', '1164.6400'), ('2018-09-11', '1177.3600'), ('2018-09-12', '1162.8200'), ('2018-09-13', '1175.3300'), ('2018-09-14', '1172.5300'), ('2018-09-17', '1156.0500'), ('2018-09-18', '1161.2200'), ('2018-09-19', '1171.0900'), ('2018-09-20', '1186.8700'), ('2018-09-21', '1166.0900'), ('2018-09-24', '1173.3700')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['g(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24','1248.0800'), ('2018-09-24', '1173.3700')]\"]\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n ['g(fermeture, 2018-11-23, 2018-11-23)']\nVotre erreur est :  Traceback (most recent call last):\n  File \"Projet1.py\", line 75, in <module>\n    fonction_premiere()\n  File \"Projet1.py\", line 69, in fonction_premiere\n    [args.debut][args.valeur],\nKeyError: datetime.date(2018, 11, 23)\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: Projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture, ouverture, min, max, volume}]\n                  symbol\nProjet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689908')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23576655')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: Projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture, ouverture, min, max, volume}]\n                  symbol\nProjet1.py: error: unrecognized arguments: aapl\n\n\n</pre>"}, {"\u00e9quipe": "019", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', \"[('2018-07-24', '1248.0800'), ('2018-09-24', '1173.3700')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 76, in <module>\n    DAT = dates(ARGUMENTS.f, ARGUMENTS.d)\n  File \"projet1.py\", line 16, in dates\n    year, month, day = map(int, fin.split('-'))\nAttributeError: 'datetime.date' object has no attribute 'split'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-f DATE] [-d DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  Traceback (most recent call last):\n  File \"projet1.py\", line 76, in <module>\n    DAT = dates(ARGUMENTS.f, ARGUMENTS.d)\n  File \"projet1.py\", line 16, in dates\n    year, month, day = map(int, fin.split('-'))\nAttributeError: 'datetime.date' object has no attribute 'split'\n\n\n</pre>"}, {"\u00e9quipe": "021", "score": 100, "commentaires": ""}, {"\u00e9quipe": "022", "score": 86, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole\nprojet1.py: error: unrecognized arguments: --fin=2018-09-24\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '689910')]\", 'aapl(volume, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '23581538')]\"]\nVotre r\u00e9ponse \u00e9tait : \n []\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole\nprojet1.py: error: unrecognized arguments: aapl\n\n\n</pre>"}, {"\u00e9quipe": "023", "score": 85, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVotre r\u00e9ponse \u00e9tait : \n [\"Aucune date de d\u00e9but entr\u00e9e : date d'aujourd'hui utilis\u00e9e\", \"Aucune date de fin entr\u00e9e : date d'aujourd'hui utilis\u00e9e\", 'goog(fermeture, 2018-11-23, 2018-11-23)', \"[('2018-11-23', '1023.8800')]\"]\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', \"[('2018-09-21', '4405584'), ('2018-09-24', '1271017')]\"]\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n [\"Aucune date de d\u00e9but entr\u00e9e : date d'aujourd'hui utilis\u00e9e\", \"Aucune date de fin entr\u00e9e : date d'aujourd'hui utilis\u00e9e\", \"Le symbole entr\u00e9 n'existe pas\", 'goog(volume, 2018-11-23, 2018-11-23)', \"Le symbole entr\u00e9 n'existe pas\", 'aapl(volume, 2018-11-23, 2018-11-23)']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "024", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n[\"Votre erreur est :  S.V.P. limitez l'utilisation du programme \u00e0 5 requ\u00eates par minute.\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\\n\"] </pre>"}, {"\u00e9quipe": "025", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "026", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  -v volume goog aapl\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-11-23, 2018-11-23)', '[]', 'aapl(volume, 2018-11-23, 2018-11-23)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\n\n</pre>"}, {"\u00e9quipe": "027", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 90, in <module>\\n    newdico = dicoresponse[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "029", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 82, in <module>\\n    fct1()\\n  File \"projet1.py\", line 75, in fct1\\n    if response[\\'Time Series (Daily)\\'].get(str(date1)) is not None:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "029", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "030", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "030", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 226, in <module>\\n    affichage(s)\\n  File \"projet1.py\", line 200, in affichage\\n    dic_bourse = response[\\'Time Series (Daily)\\'][date_ouver_converti]\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "031", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 22, in <module>\\n    sortie()\\n  File \"projet1.py\", line 9, in sortie\\n    duree = setup.jours_semaine()\\n  File \"/mnt/Documents/Projets/Laval/TA/Partie1/unbundled/bundle-031-02.hg/setup.py\", line 93, in jours_semaine\\n    info = information(\\'goog\\')\\n  File \"/mnt/Documents/Projets/Laval/TA/Partie1/unbundled/bundle-031-02.hg/setup.py\", line 65, in information\\n    return response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "032", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 97, in <module>\\n    new_dict = response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "033", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 124, in <module>\\n    print(\\'{}({}, {}, {})\\'.format(infos.indice_boursiers(), infos.variable,\\n  File \"projet1.py\", line 97, in indice_boursiers\\n    return self.dictio[\\'Meta Data\\'][\\'2. Symbol\\']\\nKeyError: \\'Meta Data\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "035", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 6, in <module>\\n    import numpy\\nModuleNotFoundError: No module named \\'numpy\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "036", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet-1.py\", line 6, in <module>\\n    import holidays\\nModuleNotFoundError: No module named \\'holidays\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "039", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 106, in <module>\\n    affichage(RESPONSE, s, ARGS.valeur, DATE_DEBUT, DATE_FIN)\\n  File \"projet1.py\", line 29, in affichage\\n    if reponse[\\'Time Series (Daily)\\'].get(debut.isoformat()):\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "040", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 74, in <module>\\n    main()\\n  File \"projet1.py\", line 40, in main\\n    liste.append((d_debut, response[\\'Time Series (Daily)\\'][d_debut][dic[mode]]))\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "042", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n[\"Votre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\\n                  [-v,--valeur {fermeture,ouverture,min,max,volume}]\\n                  symbole [symbole ...]\\nprojet1.py: error: unrecognized arguments: -v=volume\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\\n\"] </pre>"}, {"\u00e9quipe": "043", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n[\"Votre erreur est :  usage: projet1.py [-h] [-start DATE] [-end DATE]\\n                  [-value {fermeture, ouverture, min, max, volume}]\\n                  symbole [symbole ...]\\nprojet1.py: error: unrecognized arguments: -v=volume -d=2018-09-21 -f=2018-09-24\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\\n\"] </pre>"}, {"\u00e9quipe": "044", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "045", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 42, in <module>\\n    nouveau_dico = response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "046", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "047", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 94, in <module>\\n    donn\u00e9es(DEBUT, FIN)\\n  File \"projet1.py\", line 80, in donn\u00e9es\\n    don = RESPONSE[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "048", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 20, in <module>\\n    print(\\'{}({}, {}, {}\\'.format(args.symboles, args.v, args.f, args.d))\\nAttributeError: \\'Namespace\\' object has no attribute \\'v\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "049", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 105, in <module>\\n    calcul_boursier(ARGS.symbole)\\n  File \"projet1.py\", line 98, in calcul_boursier\\n    tuple1 = (str(DEBUT), response[\\'Time Series (Daily)\\'][str(DEBUT)][str(variable)])\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "050", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 83, in <module>\\n    response[\\'Time Series (Daily)\\']\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "051", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n[\"Votre erreur est :  Seulement 5 titres boursier peuvent \u00ebtre analys\u00e9s par minute\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d'impl\u00e9mentation sur le fonctionement basique\\n\"] </pre>"}, {"\u00e9quipe": "052", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 111, in <module>\\n    affichage_final(ARGS.symbole, ARGS.d\u00e9but, ARGS.fin, ARGS.valeur)\\n  File \"projet1.py\", line 104, in affichage_final\\n    afficher_ieme_symbole(symbole, debut, fin, valeur)\\n  File \"projet1.py\", line 90, in afficher_ieme_symbole\\n    for key, value in dict_titre_boursier(debut, symbole)[\"Time Series (Daily)\"].items():\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "053", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 79, in <module>\\n    display()\\n  File \"projet1.py\", line 17, in display\\n    print(request_data_alphavantage(symbole))\\n  File \"projet1.py\", line 40, in request_data_alphavantage\\n    for date in response[\\'Time Series (Daily)\\']:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "054", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 125, in <module>\\n    main()\\n  File \"projet1.py\", line 120, in main\\n    res = traitment_donnee(req, arg)\\n  File \"projet1.py\", line 90, in traitment_donnee\\n    for cle_date_requete in reponse_api[\\'Time Series (Daily)\\']:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "055", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 86, in <module>\\n    affichage(donnees(DEBUT, FIN, b), DATES, VALEUR)\\n  File \"projet1.py\", line 71, in affichage\\n    if dico[\\'Time Series (Daily)\\'].get(i) is not None:\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "056", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "057", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "058", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.</pre>"}, {"\u00e9quipe": "059", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 106, in <module>\\n    afficherfinal(ARGS.symbole, ARGS.valeur, ARGS.d\u00e9but, ARGS.fin)\\n  File \"Projet1.py\", line 99, in afficherfinal\\n    afficherlisteval(symbole, valeur, debut, fin)\\n  File \"Projet1.py\", line 85, in afficherlisteval\\n    for i, value in dictvaleurs(symbole, \\'compact\\')[\\'Time Series (Daily)\\'].items():\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "060", "score": 0, "commentaires": "<pre> Il n'y avait pas de fichier projet1.py dans le dossier de votre bundle </pre>"}, {"\u00e9quipe": "061", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :    File \"projet1.py\", line 34\\n    import argparse\\n         ^\\nIndentationError: expected an indented block\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "062", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 124, in <module>\\n    sortie(d\u00e9but, fin, alphavantage(x))\\n  File \"Projet1.py\", line 112, in sortie\\n    if str(ddate) in response[\\'Time Series (Daily)\\'].keys():\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "063", "score": 60, "commentaires": "<pre>Vous avez \u00e9chou\u00e9 le test :  -d=2018-07-24 -f=2018-09-24 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n ['goog(fermeture, 2018-07-24, 2018-09-24)', '[]']\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVous avez \u00e9chou\u00e9 le test :  --valeur=volume --fin=2018-09-24 --d\u00e9but=2018-09-21 goog\nLa bonne r\u00e9ponse \u00e9tait : \n ['goog(volume, 2018-09-21, 2018-09-24)']\nVotre r\u00e9ponse \u00e9tait : \n []\nL'erreur permise de correction \u00e9tait :\nTraceback (most recent call last):\n  File \"../../ScriptCorrection/Corrige.py\", line 69, in <module>\n    symbol, args.value, args.start, args.end))\n  File \"../../ScriptCorrection/Corrige.py\", line 28, in fetch_data_from_alphavantage\n    values = response['Time Series (Daily)']\nKeyError: 'Time Series (Daily)'\n\nVotre erreur est :  usage: projet1.py [-h] [-d DATE] [-f DATE]\n                  [-v {fermeture,ouverture,min,max,volume}]\n                  symbole [symbole ...]\nprojet1.py: error: unrecognized arguments: --d\u00e9but=2018-09-21\n\n\n</pre>"}, {"\u00e9quipe": "064", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"Projet1.py\", line 75, in <module>\\n    affichage(ARGS.symbole, ARGS.valeur, ARGS.d\u00e9but, ARGS.fin)\\n  File \"Projet1.py\", line 69, in affichage\\n    liste = list(tuple((datedebut, response[\\'Time Series (Daily)\\'][datedebut][vd])))\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}, {"\u00e9quipe": "066", "score": 0, "commentaires": "<h3> Votre programme n'a pas fonctionn\u00e9 durant la correction... </h3><pre> Un premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9t\u00e9 effectu\u00e9 mais votre programme \u00e0 soulev\u00e9 une erreur.\n['Votre erreur est :  Traceback (most recent call last):\\n  File \"projet1.py\", line 100, in <module>\\n    main()\\n  File \"projet1.py\", line 51, in main\\n    data[\\'Time Series (Daily)\\'],\\nKeyError: \\'Time Series (Daily)\\'\\n\\n\\n    Le premier test (-v=volume -d=2018-09-21 -f=2018-09-24 goog) \u00e0 \u00e9chou\u00e9.\\nIl y \u00e0 peut-\u00eatre une boucle infinie ou une erreur d\\'impl\u00e9mentation sur le fonctionement basique\\n'] </pre>"}]